### ISSUE TITLE
Verification link expires immediately

### ISSUE THREAD

**Issue by blakepm2** [uiuc-mcs/uiuc-mcs#9]
When a user tries to verify their account in order to manage their profile or create a review, the verification link expires as soon as its accessed.

**Comment by djoldman** [comment]
Please try again.

**Comment by blakepm2** [comment]
![image](https://github.com/uiuc-mcs/uiuc-mcs/assets/144281493/61d5c3d4-a051-4e09-97cb-6da6e2877e5a)

This error is returned as soon as I click on the link to verify

**Comment by djoldman** [comment]
blakepm2: it appears that your email address is already verified.

**Comment by blakepm2** [comment]
Well then the issue must lie elsewhere. I'm not able to look at my profile or create reviews on the site and am prompted to verify my email whenever I try. Here is a screenshot of the error message I see when I'm signed in and attempt to any of these actions:

![image](https://github.com/uiuc-mcs/uiuc-mcs/assets/144281493/8421ed81-f888-495e-9618-eadb1b331e6f)

From here, I'm redirected to this page and forced to verify again but get an error saying the link has expired or already been used. 

![image](https://github.com/uiuc-mcs/uiuc-mcs/assets/144281493/6feab4f5-5404-4417-8cf8-769c448ece68)

**Comment by djoldman** [comment]
I reset your password; let me know if this works. If not, I will reset your account.

**Comment by blakepm2** [comment]
Same issue unfortunately. I tried signing out and back in and verifying multiple times but get the same error. If you think resetting my account may help, please do. Thanks for your support with this!

**Comment by djoldman** [comment]
Ok, I fully reset it; try registering again.

**Comment by blakepm2** [comment]
Looks like I'm still getting the same error even after creating a new account :(

**Comment by djoldman** [comment]
Ok, I'll have to dig into this.

**Comment by djoldman** [comment]
Thanks very much for bringing this to my attention; this should be fixed. I reset your password and you should now be able to login and verify your email address.

For the curious, the issue was the same as reported here:
https://stackoverflow.com/questions/41145370/firebase-only-sends-already-expired-email-verification-links

Please reopen this issue if it is not resolved.

**Comment by djoldman** [comment]
Thanks very much for bringing this to my attention; this should be fixed. I reset your password and you should now be able to login and verify your email address.

For the curious, the issue was the same as reported here:
https://stackoverflow.com/questions/41145370/firebase-only-sends-already-expired-email-verification-links

Please reopen this issue if it is not resolved.

**Comment by blakepm2** [comment]
Thank you for fixing this. Also just want to say I really like your site and appreciate the work you put in to keep it running. It's extremely helpful!
